# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Bill_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apphotel.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateTimeField()),
                ('out_date', models.DateTimeField()),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=256)),
                ('telephone', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pay_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_room', models.CharField(max_length=3)),
                ('is_reserved', models.BooleanField()),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apphotel.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Room_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apphotel.Rating')),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apphotel.Room', verbose_name='Room')),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=15, verbose_name='Room Type')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='name_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphotel.Room_type', verbose_name='Room Type'),
        ),
        migrations.AddField(
            model_name='rent',
            name='name_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphotel.Room_type', verbose_name='Room Type'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphotel.Customer'),
        ),
        migrations.AddField(
            model_name='bill_payment',
            name='pay_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apphotel.Pay_type'),
        ),
        migrations.AddField(
            model_name='bill',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphotel.Booking'),
        ),
        migrations.AddField(
            model_name='bill',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphotel.Rent'),
        ),
    ]
